### ISSUE TITLE
Documentation on anti-csrf token is out of date

### ISSUE THREAD

**Issue by madflow** [blitz-js/blitzjs.com#149]
I _think_ that the documentation where the `anti-csrf token` is stored is out of date. Assuming that ` localstorage` means the Browser's `localStorage`.

* https://blitzjs.com/docs/auth

From a quick glance at the Dev tools in my browser: I would assume that the `anti-csrf token` is stored in a cookie - which is probably a good thing.

**Comment by flybayer** [comment]
Yes, you are right! That needs updated. We also added a helper function to get the token:

```ts
import {getAntiCSRFToken} from 'blitz'

const antiCsrf = getAntiCSRFToken()
```

Want to make a PR for this?
