### ISSUE TITLE
Add a "Made with Blitz" page

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitzjs.com#154]
I want a top-level "Made with Blitz" page (not under /docs) where anyone can add their app or project that they have built with Blitz.

It can be some type of basic grid layout where you have an title and image that links to the project.

**Comment by cardotrejos** [comment]
I would like to take this too. :D

**Comment by flybayer** [comment]
Awesome, it's all yours! 

Basically what I'm picturing is the basic grid layout like on https://www.gatsbyjs.com/showcase.

The whole site is going to get redesigned soon (design is being finalized), so you don't have to worry too much about perfect design.

**Comment by cardotrejos** [comment]
Hey there @flybayer someone already have this task on this issue https://github.com/blitz-js/blitzjs.com/issues/36.

**Comment by flybayer** [comment]
@cardotrejos I closed that one :)

**Comment by LoriKarikari** [comment]
I'm hyped for this one! Really looking forward to seeing what other projects are being built with Blitz.

**Comment by abuuzayr** [comment]
Now that we have V2 up and running, can we revive this? 

Off the top of my head, here's what's needed:
- a new layout
- a top level page, probably `pages/showcase`?
- page should be `.mdx` so its easy for anyone to add their app
-- title
-- image
-- description
-- URL

**Comment by cardotrejos** [comment]
I removed the assignment, because I don't have much time to do this :disappointed:

**Comment by flybayer** [comment]
@abuuzayr yes!

**Comment by sean-brydon** [comment]
After our talk on discord - Could this be assigned to me please :)

**Comment by abuuzayr** [comment]
absolutely! thank you @sean-brydon

**Comment by sean-brydon** [comment]
I have a basic version in my local development branch but being swamped with uni work atm - happy to pick this up once I'm finished :)

**Comment by flybayer** [comment]
@sean-brydon want to push up a draft PR? Then maybe someone else can finish it if they want

**Comment by rabbihossain** [comment]
Anyone working on it? I think i can help.

**Comment by abuuzayr** [comment]
@rabbihossain please go ahead! i'd wanted to do this for the longest time but never got a chance to. Let us know if you need anything.

**Comment by rabbihossain** [comment]
Here is a basic idea of the page I am thinking of. Anyone has any idea? Should I make e PR or anything you want to add on this page? Also, anyone please share all the sites that is made with Blitz. So that I can add a bunch of website before making a PR.

https://user-images.githubusercontent.com/4346154/124019588-0d71f680-da0b-11eb-9fba-6b34d0fc2c9f.mp4

**Comment by abuuzayr** [comment]
@rabbihossain this looks good as a start! what happens when you click? 

here is a list of apps built with blitz: https://github.com/blitz-js/blitz/wiki#-made-with-blitz-include-link-to-repo-if-open-source

i think you got the layout done:

- [x] a new layout
- [ ] a top level page, probably pages/showcase?
- [ ] page should be .mdx so its easy for anyone to add their app, with these to begin with
-- title
-- image
-- description
-- URL

**Comment by rabbihossain** [comment]
@abuuzayr  Currently it doesn't do anything when you click. My plan is to open that website when you click. 

It is a top level page . But it is not `.mdx` but I have added an extra config js file where anyone can add their website without changing any of the jsx or component codes. 

Also thanks for the list of websites. I think I can take screenshots and add these websites. After that make a PR with everything. If you have any feedback on anything, please let me know.

**Comment by abuuzayr** [comment]
thanks @rabbihossain! you can open the PR as a draft first, easier for anyone to see and make comments if they need to

it might be good to also allow some space for a description of the app/website either in your grid or in a modal popup, so visitors will have a rough idea of what the app is about before deciding to click. what do you think?

**Comment by rabbihossain** [comment]
@abuuzayr  I have created a Pull Request. Anyone can test that page on `/showcase` page after `yarn dev`.

Currently when you click on a thumbnail, it will open a popup. On that popup, if you click on image or title text it will open that website in a new browser tab.

Here is a screen recording of it.

https://user-images.githubusercontent.com/4346154/124171275-2a213380-daca-11eb-83e9-98191d26b42f.mp4

**Comment by abuuzayr** [comment]
Looks awesome. lets ship it! i think we can make modifications later.. cant wait to see the page!

**Comment by JuanM04** [comment]
@rabbihossain Wow! It's amazing!
