### ISSUE TITLE
Add Algolia to Docusaurus

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#16]
Setup the algolia docusaurus integration once some initial documentation is in place and we meet the requirements outlined in DocSearch's checklist.

[Link to DocSearch site](https://docsearch.algolia.com/)
[Link to Checklist](https://docsearch.algolia.com/docs/who-can-apply/)

- [ ] Apply to DocSearch
- [ ] Integrate DocSearch into Docusaurus once application is approved

**Comment by Kosai106** [comment]
Taken care of 😎 https://github.com/blitz-js/blitzjs.com/pull/43
