### ISSUE TITLE
Set up a Github action to run `yarn lint`

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitzjs.com#19]
- [ ] Set up a github action to run `yarn lint` on this repo

**Comment by jasonblalock** [comment]
@flybayer I see you've unassigned Michael and now opened it up for everyone. Out of curiosity, any reason you didn't just reopen #9 and merge it?

**Comment by flybayer** [comment]
@jasonblalock ah, I'm so sorry! I totally forgot about that issue and your comment in it. Looks like you added a github action on a branch but never opened a PR for it? (https://github.com/blitz-js/blitzjs.com/compare/github-actions)

If you update that to also run the linter, then we can definitely go ahead and use yours. ❤️
