### ISSUE TITLE
Add Blitzjs to docusaurus v2 showcase

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#2]
Once branding is complete and the website is up and running, add the blitzjs logo to the showcase page for docusaurus v2.

add the logo file here: https://github.com/facebook/docusaurus/tree/master/website/src/data/showcase
add a record in this file in alphabetical order: https://github.com/facebook/docusaurus/blob/master/website/src/data/users.js

**Comment by simonpeterdebbarma** [comment]
@robdrosenberg Pretty sure this can be closed so I'm gonna go ahead and do that.

**Comment by flybayer** [comment]
@simonpeterdebbarma this isn't done until Blitz is listed in the below file :)

https://github.com/facebook/docusaurus/blob/master/website/src/data/users.js

**Comment by simonpeterdebbarma** [comment]
Thanks for the information @flybayer. I'll make sure I ask every time before closing any Issues in the future.

**Comment by LoriKarikari** [comment]
Is this something that can be done now?

**Comment by flybayer** [comment]
Wait till the final design :)
