### ISSUE TITLE
Website Design

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#23]
Kristina Matuska will be working on the website design

### Proposed Site pages / Content
- Home Page
- Docs -> Guides | Tutorials | API
- Showcase
- About -> Community | Sponsors
- Blog
- Releases
- FAQ

### Design Phases
**Stage 1**: Start off with a detailed wire frame of the home page
**Stage 2**: Build out the content architecture / wireframes for the other pages with less detail than home page
**Stage 3**: Complete Home Page design
**Stage 4**: Site / Brand Style guide

**Comment by simonpeterdebbarma** [comment]
Is this 'In Progress' or 'Done'?

**Comment by robdrosenberg** [comment]
### Proposed Site pages / Content
- Home Page
- Docs -> Guides | Tutorials | API
- Showcase
- About -> Community | Sponsors
- Blog
- Releases
- FAQ

### Design Phases
Stage 1: Start off with a detailed wire frame of the home page
Stage 2: Build out the content architecture / wireframes for the other pages with less detail than home page
Stage 3: Complete Home Page design
Stage 4: Site / Brand Style guide

**Comment by peterpalau** [comment]
Hi guys, I want to collaborate with this one. Is there anything I can do?

**Comment by flybayer** [comment]
@peterpalau are you in our Slack? Our designer Kristina has some stuff you can help with :)

**Comment by peterpalau** [comment]
> @peterpalau are you in our Slack? Our designer Kristina has some stuff you can help with :)

Ok @flybayer I will do it.
