### ISSUE TITLE
Initial Blitz cli commands

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#24]
Create alpha documentation for getting blitz up and running locally and cli commands.

- [ ] Highlight blitz cli commands
- [ ] Initial Blitz project setup

**Comment by flybayer** [comment]
I have an alpha guide here with everything needed for the alpha (I think): https://github.com/blitz-js/blitz/pull/131

So that's a good starting point for this issue.

**Comment by coreybrown89** [comment]
@flybayer thanks - this is super helpful.
