### ISSUE TITLE
Docs - how to prettier configuration

### ISSUE THREAD

**Issue by theZieger** [blitz-js/blitzjs.com#248]
### What do you want and why?

As of https://github.com/blitz-js/blitz/discussions/1390 I noticed there is no documentation that guides one about how to change certain (opinionated) aspects of Blitz. Therefore I would like to see a new page within the advanced section of the documentation: *Prettier Config*

### Possible implementation(s)

Add a new page to the docs. :rocket: 

### Additional context

I get that an opinionated framework like Blitz has a lot of benefits but some companies can be very restrictive in how developers should write their code. Or they already established a certain code style. That's why I think we should guide everyone who really wants to change the prettier configuration a little bit better around in how to do so.

**Comment by flybayer** [comment]
We can add a general page like "Creating a new app" that can cover this and other things like form libraries, etc.

**Comment by Roesh** [comment]
Just saw this when I was looking to make sure we didnt have an issue open for adding typescript config changes to the docs. 

The prettier configuration mentioned in the title is complete, but @flybayer let me know if there needs to be a separate "Creating a new app" page still.
