### ISSUE TITLE
V2 - Initial Setup

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#249]
We're ready to start the new version of the Blitzjs.com site.

We'd like to build it using Blitz and Tailwind.

The initial idea is to fork the [Tailwind Docs Site](https://github.com/tailwindlabs/tailwindcss.com) and add Blitz to it and use Tailwind for Styling. We'd use static rendering where ever possible. Auth isn't needed right now but there could be use cases later on that we could build!

- [ ] Create a new V2 Branch
- [ ] Setup a starter Blitz app
- [ ] Add Tailwind

**Comment by cwray-tech** [comment]
Hey, @robdrosenberg I added a v-2 branch. Tomorrow I can start working on the setup of the Blitz app based on the Tailwind CSS website as Brandon has suggested.
