### ISSUE TITLE
V2 - Video Component

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#252]
Create a video component we can reuse anywhere on the site. Should be able to handle videos from platforms like Youtube, Vimeo, and any other kind of video link including files.

Some libraries that do the job well I've used before:
[react-player](https://github.com/CookPete/react-player)
[video-react](https://video-react.js.org/)

**Comment by flybayer** [comment]
This has the best performance: https://github.com/paulirish/lite-youtube-embed

**Comment by flybayer** [comment]
v2 code is now in the `new-site` folder of the main branch
