### ISSUE TITLE
V2 - Nav

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#253]
Create the site nav in light and dark mode and display it on all pages.

We will update this list as new issues get created but here are the other requirements for the nav to be complete.
- [ ] Add docs search to nav
- [ ] Light / Dark mode theme switcher
- [ ] Banner component for announcements
- [ ] Mobile Nav

Links:
- [ ] Docs page
- [ ] Github - https://github.com/blitz-js/blitz
- [ ] Releases - https://github.com/blitz-js/blitz/releases
- [ ] Slack - https://slack.blitzjs.com/
- [ ] Forum - https://github.com/blitz-js/blitz/discussions
- [ ] Donate - https://github.com/sponsors/blitz-js

Design:
https://www.figma.com/file/KxLHA7cVPEy1fNE2bD8wWv/Blitz?node-id=269%3A1
![navbar](https://user-images.githubusercontent.com/20813991/99104557-fd012e80-2595-11eb-924f-655885d718d9.png)
![navbar](https://user-images.githubusercontent.com/20813991/99104597-0ab6b400-2596-11eb-8cdf-e5a09bf86d9a.png)
![BLITZ_375_MenuOpen](https://user-images.githubusercontent.com/20813991/99104636-1ace9380-2596-11eb-8e76-35473f2d7028.png)

**Comment by flybayer** [comment]
v2 code is now in the `new-site` folder of the main branch

**Comment by Flavyoo** [comment]
Does it make sense to split this implementation into two components. One for the call out at the top and one for the navbar? I can create the issue for the callout.

**Comment by flybayer** [comment]
@Flavyoo yes, probably makes sense.

**Comment by Flavyoo** [comment]
@robdrosenberg Is there a way to create a template from the issue you have here?
