### ISSUE TITLE
V2 - Remove all the Tailwind specific content and code

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitzjs.com#255]
The v2 site is now in the `new-site` folder on the main branch.

It currently it's a clone of the tailwindcss doc site, so now we need to remove all the tailwind docs, images, tailwind specific components (can keep anything generic that looks useful), etc.

Let me know if you have questions about anything.

**Comment by cwray-tech** [comment]
I can work on this if no one else is!

**Comment by flybayer** [comment]
@cwray-tech ok, just wait until I get #269 fixed and merged

**Comment by cwray-tech** [comment]
@flybayer sounds good.

**Comment by cwray-tech** [comment]
Starting on this!

**Comment by cwray-tech** [comment]
@flybayer great work! Thank you for taking over!
