### ISSUE TITLE
V2 - Page Layout

### ISSUE THREAD

**Issue by Flavyoo** [blitz-js/blitzjs.com#256]
Create a page layout component. 

Requirements:

- [ ] Contents can be passed to this layout component to render the pages.

- [ ] Support for adding contents to the header of the HTML page such as meta tags and page titles using the Blitz `<Head/>` component

Design:
https://www.figma.com/file/KxLHA7cVPEy1fNE2bD8wWv/Blitz?node-id=1147%3A0

**Comment by flybayer** [comment]
We don't need react-helmet, blitz has a `<Head>` component that does the same thing.

**Comment by flybayer** [comment]
Already done
