### ISSUE TITLE
V2 - Banner

### ISSUE THREAD

**Issue by Flavyoo** [blitz-js/blitzjs.com#257]
Create a banner component that can be used to make announcements on the site.

Requirements:

- [ ] Follow current design linked below

- [ ] Take the announcement content as a prop. Consider how we can store the announcement so it can be easily updated and translated. Maybe store it in an MDX file?

- [ ] Might be worth to render this banner component as part of the Page Layout component. This way we don't have to import it and render it in each page we make.

- [ ] Responsive, follows mobile design in Figma

Designs:
Figma: https://www.figma.com/file/KxLHA7cVPEy1fNE2bD8wWv/Blitz?node-id=1147%3A0

![banner-component](https://user-images.githubusercontent.com/14948074/99151643-a4e82c00-266a-11eb-9443-a4b29a691814.png)

**Comment by abuuzayr** [comment]
i'll work on this if nobody is on this yet!

**Comment by Flavyoo** [comment]
@abuuzayr Thanks for picking this up. Let me know if I can help with anything, and please add me to the review.
