### ISSUE TITLE
V2 - Configure Tailwind light/dark theme

### ISSUE THREAD

**Issue by Flavyoo** [blitz-js/blitzjs.com#258]
The new site has a dark and light theme that users can switch between in the Navbar. The objective of this issue is to create the theme object supported by Tailwind for both dark and light mode.

- [ ] Dark and light mode theme configured
- [ ] [Follow the figma style guide](https://www.figma.com/file/KxLHA7cVPEy1fNE2bD8wWv/Blitz?node-id=1130%3A2472)

**Note: we need to use the new tailwind dark mode that was added as [an experimental option in 1.8.0](https://github.com/tailwindlabs/tailwindcss/releases/tag/v1.8.0#dark-mode-experimental).**

Links:
[Tailwind CSS Theme Docs](https://tailwindcss.com/docs/theme)

**Comment by flybayer** [comment]
I added a line to your message about using the new tailwind dark mode feature.

**Comment by Flavyoo** [comment]
Sounds good!

**Comment by flybayer** [comment]
done
