### ISSUE TITLE
V2 - Blitz Description Component

### ISSUE THREAD

**Issue by Flavyoo** [blitz-js/blitzjs.com#259]
Create the component that contains the main page header and description.

- [ ] Contains the proper page header and description for Blitz

- [ ] Follows the figma design. Other half of this section looks like a background image based on how the hands wrap the code sample. This component can take the whole width and have contents aligned left.

- [ ] Responsive, follows mobile design in Figma

**Suggestion**: This component should also render the action items since the section can be split into two parts. One with the description and an image to go along with it. In case we decide to switch the background image to having just an image on the right, the contents will be aligned well.

Design:

https://www.figma.com/file/KxLHA7cVPEy1fNE2bD8wWv/Blitz?node-id=1147%3A0

Resources
![page-desription](https://user-images.githubusercontent.com/14948074/99152199-4de45600-266e-11eb-9db6-7679dd0a9cda.png)

**Comment by flybayer** [comment]
Also needs to be responsive (mobile design is in figma)
