### ISSUE TITLE
Update Socials

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#26]
- Slack
- [Twitter](https://twitter.com/blitz_js)
- Open Collective
- Github

**Comment by flybayer** [comment]
All of these are already done, I think!

**Comment by mgm1313** [comment]
> All of these are already done, I think!

Open Collective is not yet shown on the site. Should that one be added to the footer as well?

**Comment by flybayer** [comment]
@mgm1313, yes let's add that

**Comment by simonpeterdebbarma** [comment]
Closed in https://github.com/blitz-js/blitzjs.com/pull/39
