### ISSUE TITLE
V2 - Background Component

### ISSUE THREAD

**Issue by Flavyoo** [blitz-js/blitzjs.com#260]
Create the Background component.

The Background component is responsible for rendering any background we want. Right now we have two types of Background, a plain color background and an Image based background. Backgrounds will be used on different sections of a page.

Requirements:
- [ ] The component should take an image or image resource as a prop and render it if it is an image background.

- [ ] Follow Blitz pattern for working with static files.

- [ ] [Use Next JS Image if possible](https://nextjs.org/docs/api-reference/next/image)

- [ ] Background images include proper accessibility attributes

- [ ] [Follows Figma design](https://www.figma.com/file/KxLHA7cVPEy1fNE2bD8wWv/Blitz?node-id=1147%3A0)

Links:
Figma: https://www.figma.com/file/KxLHA7cVPEy1fNE2bD8wWv/Blitz?node-id=1147%3A0

**Comment by rembrandtreyes** [comment]
🙌 I'll grab this.

**Comment by flybayer** [comment]
@rembrandtreyes it's actually already done!
