### ISSUE TITLE
V2 - Add a custom scrollbar for the homepage

### ISSUE THREAD

**Issue by scisteffan** [blitz-js/blitzjs.com#306]
The architecture diagram and the "Everything You Need For Production Apps" features list need a custom scrollbar so it's visible and obviously scrollable.

**Comment by rembrandtreyes** [comment]
I'll grab this. Are there designs set for the horizontal scroll bar? If not I'll make it similar to the new design.

**Comment by scisteffan** [comment]
> Are there designs set for the horizontal scroll bar?
No 😄
