### ISSUE TITLE
V2: Add a cookie message for EU visitors (GDPR)

### ISSUE THREAD

**Issue by scisteffan** [blitz-js/blitzjs.com#318]
Since we have a target audience of people in the EU, then we need to add a cookie popup consenting to the use of cookies on the website - to comply with GDPR regulation in the EU. This can be just a small dialog box at the bottom of the page on the first pageload. It should not display on future visits. We can use GeoIP to determine the location of the visitor.

**Comment by flybayer** [comment]
Do we _really_ have to? 😅

**Comment by scisteffan** [comment]
https://www.lexology.com/library/detail.aspx?g=8be3232c-11a4-45b7-b8d9-3a54844e77aa

> Simply having a website that's accessible in the EU doesn't bring your business within the GDPR's scope. But if your website targets EU consumers at least in part by, for example, accepting ecommerce payments in Euros as an alternative to U.S. dollars, or if the site's use of cookies amounts to intentionally "monitoring" the behavior of visitors who are in the EU, the GDPR likely applies, and you should at least consider the need for a cookie banner to help comply with the GDPR's notice and consent requirements.

We don't need to add the cookie banner. That's a relief.
