### ISSUE TITLE
V2: Dark mode toggle flips back to 'light' mode on refresh

### ISSUE THREAD

**Issue by rembrandtreyes** [blitz-js/blitzjs.com#320]
When a user lands on the new https://next.blitzjs.com/ site click on the dark mode toggle it will switch the theme to dark mode and save the state of the theme.

Now if the user refreshes the page the dark mode toggle will switch back to light mode, but leaves the theme set to dark.

![dekstop](https://user-images.githubusercontent.com/15057964/104220030-c60f9380-53f3-11eb-9109-8e0a3a8e4538.gif)

**Comment by scisteffan** [comment]
I'm working on this one!
