### ISSUE TITLE
Update Nav bar (Assigned to Ivan)

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#33]
- [x] Remove blog link
- [ ] Update vision link for Blitz Manifesto
- [ ] Update github link

**Comment by robdrosenberg** [comment]
Assigned to @IvanB475

**Comment by simonpeterdebbarma** [comment]
Closed this Issue as task is completed in https://github.com/blitz-js/blitzjs.com/pull/39
