### ISSUE TITLE
Edition link to improve a documentation page are broken

### ISSUE THREAD

**Issue by Spy-Seth** [blitz-js/blitzjs.com#371]
In the footer of a documentation page, the "_Idea for improving this page? Edit it on Github._" links lead to a 404. 

![image](https://user-images.githubusercontent.com/95120/108316965-e8988780-71bd-11eb-9390-d0274432bfc4.png)

For example:
- on the https://blitzjs.com/docs/get-started page, 
- the link lead to https://github.com/blitz-js/blitzjs.com/edit/main/docs/get-started.mdx
- it should lead to https://github.com/blitz-js/blitzjs.com/blob/main/app/pages/docs/get-started.mdx

**Comment by abuuzayr** [comment]
should it be this: https://github.com/blitz-js/blitzjs.com/edit/main/app/pages/docs/get-started.mdx?

**Comment by flybayer** [comment]
Ah yes! Here's the line that needs fixed: https://github.com/blitz-js/blitzjs.com/blob/main/app/layouts/ContentsLayout.js#L204

**Comment by Spy-Seth** [comment]
Thanks to @flybayer the issue is solved. I'm closing it
