### ISSUE TITLE
Broken links in algolia documentation search

### ISSUE THREAD

**Issue by scisteffan** [blitz-js/blitzjs.com#376]
If I enter the search phrase "invalidateQuery" the first result in the search popup goes to a broken link: https://blitzjs.com/docs/resolver-utilities#invalidatequery

**Comment by flybayer** [comment]
Looks like we need to update this config: https://github.com/algolia/docsearch-configs/blob/master/configs/blitzjs.json

Here's the docs on that config: https://docsearch.algolia.com/docs/config-file/

**Comment by scisteffan** [comment]
I think we need to ask Algolia to do it, because the setup is done by them.

See https://docsearch.algolia.com/docs/how-does-it-work

**Comment by flybayer** [comment]
Ok maybe yeah. cc @Kosai106

**Comment by Kosai106** [comment]
Thanks for the ping @flybayer - I'll notify our DocSearch team.

**Comment by shortcuts** [comment]
Hi there,

I've updated the config in https://github.com/algolia/docsearch-configs/pull/3598. You should see the changes in the next 24 hours, feel free to ping me if there's any other issue!

**Comment by scisteffan** [comment]
It's working as expected, thank you!!
