### ISSUE TITLE
Remove horizontal scroll in code examples by reformatting code blocks with smaller line width

### ISSUE THREAD

**Issue by sakulstra** [blitz-js/blitzjs.com#389]
First off: the docs are beautiful and I as an absolute blitzjs beginner have found everything i needed within seconds. Good job on that!

Little nitpick though:
![image](https://user-images.githubusercontent.com/4396533/109299541-8d0d7000-7835-11eb-9acb-3abf752486bd.png)

In most code examples i got a horizontal scrollbar making it hard to read them.
I would imagine that if the right column would use the full space (till underneath the social icons) this would be less problematic.

Wdyt? Any other suggestions? 
I'd be happy to work on that.

**Comment by flybayer** [comment]
Thanks for the feedback @sakulstra. We have a max-width on the docs for readablity for regular text. I can see how the code thing is a cumbersome though.

I think maybe the real fix is to change our prettier config so that code has a smaller line width. Ideally we could change it just for doc code blocks, but I'm not sure if that's possible or not.

**Comment by JuanM04** [comment]
> I think maybe the real fix is to change our prettier config so that code has a smaller line width. Ideally we could change it just for doc code blocks, but I'm not sure if that's possible or not.

As far as I know, is not possible. It would break `diff` code and custom indentation. I think it has to be done manually

**Comment by flybayer** [comment]
Prettier currently formats the code blocks. So it should work. It could be diff code blocks aren't formatted by prettier. not sure

**Comment by JuanM04** [comment]
I'll look into it

**Comment by JuanM04** [comment]
Ok, I found a solution. `diff` aren't formatted, so that's have to be done manually. The other codeblocks (`txt` and `bash`) also remain unformatted
