### ISSUE TITLE
<a> in Admonition blocks have very low contrast on dark theme

### ISSUE THREAD

**Issue by pizzafox** [blitz-js/blitzjs.com#397]
[Page used in screenshots](https://blitzjs.com/docs/database-overview#content-wrapper:~:text=Prisma's%20Data%20Guide)

## Dark theme

![dark theme](https://user-images.githubusercontent.com/7608555/109775599-8de82e00-7bb6-11eb-98cb-7736dea1224d.png)

## Light theme

![light theme](https://user-images.githubusercontent.com/7608555/109775604-904a8800-7bb6-11eb-9b15-f60a0b457934.png)

**Comment by flybayer** [comment]
Thanks for the report!
