### ISSUE TITLE
Light mode setting does not take effect on page load

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitzjs.com#437]
1. Set light mode on the docs
1. Open blitzjs.com in new tab
1. See that dark mode is shown, even thought dark mode toggle is set to light mode

This used to work, so not sure why it's not now. We use https://github.com/pacocoursey/next-themes, so maybe upgrading that is enough? Or maybe we need to adjust our settings with how we use that.

**Comment by JuanM04** [comment]
It seems like ThemeProvider doesn't update. Weird

**Comment by JuanM04** [comment]
May be related to this: https://github.com/pacocoursey/next-themes/issues/40

**Comment by 5minpause** [comment]
I just tried it and couldn't reproduce the behaviour mentioned by @flybayer in https://github.com/blitz-js/blitzjs.com/issues/437#issue-856076141.
I believe #485 fixed it and this issue can be closed, @JuanM04 .
