### ISSUE TITLE
Minor discrepancy in the session management docs

### ISSUE THREAD

**Issue by sean-brydon** [blitz-js/blitzjs.com#440]
In the Session Management Docs specifically  [Here](https://blitzjs.com/docs/session-management#customize-session-public-data-in-typescript). The examples is showing 

```js 
export type Role = "ADMIN" | "USER"
```
Then the example of the session being created uses a Role value of 'admin'

This is just a minor issue and would happily have this assigned to myself if this needs fixing

**Comment by flybayer** [comment]
Thanks, you can definitely fix that!
