### ISSUE TITLE
Dark mode text not changing on toggling theme

### ISSUE THREAD

**Issue by Hardik3296** [blitz-js/blitzjs.com#463]
When we click on toggle button for changing the theme on the website, the theme changes but the text in both cases always reads **Dark**,  signifying dark mode is applied, which might be confusing. 

<img width="342" alt="Text-in-dark-mode" src="https://user-images.githubusercontent.com/20360325/117180855-40748100-adf2-11eb-9383-df310a7658cf.png">

**Text in Dark Mode**

<img width="331" alt="Screenshot 2021-05-05 at 10 29 28 PM" src="https://user-images.githubusercontent.com/20360325/117180987-669a2100-adf2-11eb-9f17-064560a59c75.png">

**Text in Light Mode**

I believe we can change the text on click to either **Light** or **Dark** depending on the theme applied. I think we can also remove the border around the toggle and the text when clicked, seems a bit weird to me, if it is ok with you. Let me know.

**Comment by Hardik3296** [comment]
I will like to make this change to the site if it is ok with you. Would be my first contribution.

**Comment by flybayer** [comment]
@Hardik3296 yes please! :)
