### ISSUE TITLE
Announcement Banner Component

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#51]
We need a banner component at the top of the page.
Initially we'd like it to display: "Site Still In Progress"

In the future we can use it as a banner for announcements like new Blitz version releases. Any talks that are given on Blitz etc..

It should also have a close button so people who frequent the site don't have to see it all the time.

**Comment by 0ww** [comment]
I'd like to do this.

**Comment by 0ww** [comment]
I'll have to unassign myself from this Issue, as I am unable to solve why my components aren't rendering and causing weird bugs. For some weird reason, the whole page goes blank with my own components, or external components like `react-banner`. 

If it's any consolation to myself it compiles without error. Maybe you will have better success.

![image](https://user-images.githubusercontent.com/31207418/81255133-21c68900-8fea-11ea-8899-afacb5ba4605.png)

**Comment by liamjosephsilk** [comment]
If this is still available, it is something I would like to do.

**Comment by liamjosephsilk** [comment]
Just a couple of questions before implementing: 

1. Is the banner ok to be under the navigation bar, but maintain a fixed position? (This is because the nav is from docosaurus theming, and would require changes the the Layout component)
2. Do you want the banner displaying on all pages or just the homepage? (Again down to changes to the docosaurus theming and Layout component)

**Comment by 0ww** [comment]
I think you can have it as part of the navbar by swizzling the component from Docusaurus. Let's have it all pages, but if you close it on one page, it should not show up on other pages.

**Comment by liamjosephsilk** [comment]
My only concern with that is, in the docs it states to discourage swizzling until into Beta? I can easily implement this if agreed.

**Comment by robdrosenberg** [comment]
@liamjosephsilk Sorry if I'm too late, just getting to this but if you can avoid swizzling it's probably best for now until docusaurus v2 is more stable.

**Comment by liamjosephsilk** [comment]
That's ok, ill do it without the swizzle. I'm not sure if i'll be able to alter css for the component, because the classnames are created on build.

**Comment by robdrosenberg** [comment]
Merged in #53, Thanks @liamjosephsilk 🎉

**Comment by liamjosephsilk** [comment]
Thanks, I've been super swamped with uni work! I was trying to look at without swizzle as you suggested but just haven't had time.
