### ISSUE TITLE
Make SponsorPack images smaller or use <Image />

### ISSUE THREAD

**Issue by mdouglasbrett** [blitz-js/blitzjs.com#512]
Hi there! This is just a heads up: I ran a lighthouse test against blitzjs.com (👏  👏 ), and image referenced below is coming in at just under 2Mb 👇, must've slipped through the net
https://github.com/blitz-js/blitzjs.com/blob/240b15e59c333668998a92b2082a0a99fa2767ad/app/core/components/SponsorPack.js#L41

All the best, Mike

**Comment by JuanM04** [comment]
Good catch. We should change that to use `<Image />`
