### ISSUE TITLE
Is single threading a tradeoff of NextJS or NodeJS

### ISSUE THREAD

**Issue by jackbravo** [blitz-js/blitzjs.com#514]
On https://github.com/blitz-js/blitzjs.com/blob/main/app/pages/docs/tradeoffs.mdx its stated that a single threaded server is:

> a tradeoff of Next.js specifically

But I've read that this tradeoff is generic to NodeJS event loop model. Which is which?

This doesn't mean that spawning background processes isn't still valid.

**Comment by flybayer** [comment]
@jackbravo yes, good point! It is a Node thing. Want to PR a fix for that?

**Comment by JuanM04** [comment]
Closed by #542
