### ISSUE TITLE
Add Theme UI

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#55]
We've decided to use Theme UI as our CSS solution for the website.

We found Theme UI to be a choice that struck a good balance between Tailwind and Emotion / Styled Components. Since the community was split between both.

You can find instructions on how to install Theme UI here: https://theme-ui.com/getting-started

**Comment by robdrosenberg** [comment]
Took a first stab at it but couldn't get it to override the current styles with the time I had.
 - The first issue is the Layout Component is in the @theme directory which is default docusaurus code, not sure how to add the ThemeProvider component from theme ui to it.
- Clearing out the styles. There's a ton of default css from the docusaurus theme baked in, we'll have to strip out or override. I couldn't get everything overwritten in the amount of time I had tonight.

I'll push up the yarn package and an initial theme.js file. The settings in the theme.js aren't final but just some initial theme values to work with.

**Comment by flybayer** [comment]
Closed in #63
