### ISSUE TITLE
Add architecture diagram to `Client and Server` docs page 

### ISSUE THREAD

**Issue by beerose** [blitz-js/blitzjs.com#556]
[This PR](https://github.com/blitz-js/blitzjs.com/pull/555) added a new page to the docs on Client vs Server and what's executed where. It would be nice to include an architectural diagram as well — the same as we have on [the landing page](https://blitzjs.com/). More context here: https://github.com/blitz-js/blitzjs.com/pull/555#issue-1009856008.

**Comment by beerose** [comment]
Hey! Could I ask what's the reason behind closing it? 😅 I'm totally fine if you think it was a bad idea, but just curious.

**Comment by JuanM04** [comment]
Oh, sorry. I thought this issue was solved by that PR. My bad

**Comment by JuanM04** [comment]
What do you think about this? I did it a bit more vertical, but it may not be ideal

![light](https://user-images.githubusercontent.com/16712703/135523982-7f67c860-b574-42e6-a460-90d90b2466ee.png)
![dark](https://user-images.githubusercontent.com/16712703/135524047-e5e7f528-87ba-4545-ae9c-eb0750a7a58d.png)

**Comment by beerose** [comment]
Cool! Nice idea with a vertical approach.

**Comment by JuanM04** [comment]
Added in e546e7242e62654aad0ca82599c19a16564bdaf8

**Comment by beerose** [comment]
🎉
