### ISSUE TITLE
Bad contrast for links in notes sections in dark mode

### ISSUE THREAD

**Issue by beerose** [blitz-js/blitzjs.com#570]
It's a little difficult to read. We could change it to Blitz's purple colour.

<img width="735" alt="Screenshot 2021-10-11 at 16 55 29" src="https://user-images.githubusercontent.com/9019397/136811787-05d0245e-5686-42ad-b0c2-de4808792ade.png">

**Comment by harshndroid** [comment]
Can i get assigned to it @beerose ?
