### ISSUE TITLE
Add styling and theming

### ISSUE THREAD

**Issue by jasonblalock** [blitz-js/blitzjs.com#6]
- [ ] Theme-UI for styling and theming
- [ ] Dark mode (might be a no-op if built into docusaurus)

**Comment by simonpeterdebbarma** [comment]
Closed as this is an old issue.

**Comment by flybayer** [comment]
I don't think this is done yet

**Comment by simonpeterdebbarma** [comment]
Sorry about that. Reopening.

**Comment by simonpeterdebbarma** [comment]
Similar Issues: https://github.com/blitz-js/blitzjs.com/issues/25 and https://github.com/blitz-js/blitzjs.com/issues/28

**Comment by robdrosenberg** [comment]
Closing due to multiple similar issues.
