### ISSUE TITLE
Inconsistent Theme Switcher

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#66]
The theme switcher does not alternate positions consistently across different browsers.

I tested on Chrome and had the following result.

![CleanShot 2020-05-25 at 18 31 41](https://user-images.githubusercontent.com/20813991/82851999-6beaae00-9eb6-11ea-83d0-dd9de6e98cf1.gif)

@aem Tested on firefox and had the same issue.

### Expected behavior:
When the site is in light mode, the radial button should be on the left and display the sun.
When the site is in dark mode, the radial button should be on the right and display the moon.

**Comment by flybayer** [comment]
@robdrosenberg I'm 95% sure this is a cache issue for you because the header bar is dark which means you still have the old docusaurus theme stuff hanging in your browser. You need to clear your local storage.

**Comment by robdrosenberg** [comment]
Tested it on Firefox and Safari and did not see the issue.
Cleared my local storage and is working now on Chrome.
