### ISSUE TITLE
When the width of a web page is 1024px ~ 1300px, the text color and background color are the same, making it hard to read.

### ISSUE THREAD

**Issue by mochi-sann** [blitz-js/blitzjs.com#676]
https://user-images.githubusercontent.com/44772513/165090549-ba354b7c-421e-4d55-a68e-f1bb20c27d2f.mov

When I open https://blitzjs.com as shown in the video and the width of the web site is between 1024px and 1300px, the text color and background color are the same and very difficult to read.

**Comment by beerose** [comment]
That's weird 😅 thanks for reporting

**Comment by Himanxu1** [comment]
I cannot find this issue in my computer

**Comment by kensan73** [comment]
I cannot reproduce either

**Comment by mochi-sann** [comment]
I'm closing this Issue because the problem was resolved.
