### ISSUE TITLE
Add a restart blitz after adding choices display in tutorial

### ISSUE THREAD

**Issue by kensan73** [blitz-js/blitzjs.com#753]
Hello,

After following the tutorial I got to this step

Now hop back to our main questions page (pages/questions/index.tsx)in your editor, and we can list the choices of each question. And add this code beneath the Link in our QuestionsList:

and added the code.  I got another error about undefined count I believe (even though compilation was successful in the console) but after restarting blitz I was good to go.

**Comment by joneskj55** [comment]
I'll take this issue if still up for grabs. @beerose

**Comment by beerose** [comment]
Yes! Go ahead @joneskj55
