### ISSUE TITLE
Following the blitz tutorial at this step the code is different

### ISSUE THREAD

**Issue by kensan73** [blitz-js/blitzjs.com#754]
At this step it says to delete this line

![image](https://user-images.githubusercontent.com/10583935/187913052-cd6cd30a-1124-48f5-b22a-95b78a0b4642.png)

but I think at this step it should look like

![image](https://user-images.githubusercontent.com/10583935/187913145-de77aa99-68d9-4f0c-842c-dd471314a912.png)

**Comment by beerose** [comment]
I believe that the tutorial code is correct because our generator creates the `name` property.
Here's the source: https://github.com/blitz-js/blitz/blob/main/packages/generator/templates/mutations/update__ModelName__.ts#L7

**Comment by estevanjantsk** [comment]
@beerose I didn't understand this one, could you clarify, please? As you said, the generator creates with name (but this is expected) the tutorial has a step [before](https://github.com/blitz-js/blitzjs.com/blob/main/app/pages/docs/tutorial.mdx#updatechoice-mutation-update-choice-mutation ) that changes the name to text so this is expected and when it reaches [this](https://github.com/blitz-js/blitzjs.com/blob/main/app/pages/docs/tutorial.mdx#now-its-time-to-add-voting) the text is there and makes sense.

I think this issue should be closed.

**Comment by beerose** [comment]
Yes, you're right. Sorry for the confusion. Closing the issue
