### ISSUE TITLE
Add social preview images

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitzjs.com#79]
Currently the site doesn't have any open graph social images.

We need to add these so it looks good when shared on social media.

You can link to this image: https://github.com/blitz-js/art/raw/master/logo-bg-purple.png

**Comment by toshi1127** [comment]
I would like to tackle this issue.

**Comment by flybayer** [comment]
@toshi1127 awesome! Will be really good to get this in.

**Comment by flybayer** [comment]
Closed in #96
