### ISSUE TITLE
Add initial Github actions for CI

### ISSUE THREAD

**Issue by jasonblalock** [blitz-js/blitzjs.com#9]
- Setup Github actions to build on pull request for master and push to master

**Comment by flybayer** [comment]
I set up auto deploy via zeit now. Won't need any tests, at least for now, so don't need github actions

**Comment by jasonblalock** [comment]
@flybayer I'd like to reopen/repurpose or create a new issue around this. I think we should be running our linting/prettifying as part of our CI. It's great that we're using husky, but our CI is the last place to verify/ensure that linting has been run to prevent inconsistencies and alexjs related issues from reaching our site. It's how react/react-native docs run their CI as well. Thoughts?

Separately, I'd like to codify the now deployment into the github actions as well. They have their own plugin for github actions. I think it will make it more transparent and allow us more control, but that can be a separate issue.

**Comment by flybayer** [comment]
@jasonblalock yes, I forgot about linting when I closed this :)

I already opened #19 and assigned to Micheal — he's my devops master. I'm sure you'd do great, but I'd rather Micheal do all the devops so everything is consistent across repos, etc.
