### ISSUE TITLE
Document how to migrate a Next.js app to Blitz

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitzjs.com#90]
We want to add a guide to our docs on how to migrate a Next.js app to a Blitz app. The main thing is replacing the next dependency with blitz, and then using `blitz start` and `blitz build`.

There's probably some edge cases here that we need to document and maybe and have fixes for (like I'm not sure if `src/pages` works with Blitz?)

@ryardley do you have anything to add to this?

**Comment by LoriKarikari** [comment]
I can take a look at this later this week if no one else has started this yet. I haven't tried this yet but I'm eager to experiment with it.

**Comment by ryardley** [comment]
Yeah I am not sure `src/pages` will work. Would probably need to be moved to `app/pages` however a fix to make it work in blitz would be pretty easy.

**Comment by JuanM04** [comment]
Closed by #590
