### ISSUE TITLE
Add syntax line highlighting

### ISSUE THREAD

**Issue by flybayer** [blitz-js/blitzjs.com#98]
The default docusurus Code component [had support for highlighting specific lines](https://v2.docusaurus.io/docs/markdown-features/#line-highlighting) in a code block. But we lost that when we switched to the Prism component provided by theme-ui.

However, we really need the line highlight functionality to it's easy to highlight certain changes in the tutorial.

[Here's where it's used in our source code](https://github.com/blitz-js/blitzjs.com/blob/master/src/components/MDXComponents/index.js#L14).

I don't know if the theme-ui prism component can be extended to add this? If not, then we can take the source code of the theme-ui prism component and add that directly into your codebase. Then merge in the source code that does line highlighting from the docusaurus code component.

**Comment by shaunchurch** [comment]
Looks like support for highlighting specific lines was added to Theme-UI/Prism in the coming version 4.0, currently in RC1 release.

We can upgrade @theme-ui/prism separately to the rest of theme-ui so perhaps it's not a big risk to move to the release candidate just for Prism? Will submit a PR shortly.
